spring:
  application:
    name: email-sender
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT}
security:
  jwt:
    secret: ${SECURITY_JWT}
  header:
    clients:
      key: ${SECURITY_CLIENTS_HEADER_KEY}

email:
  from: ${EMAIL_USERNAME}